annotations:
  category: DeveloperTools
  artifacthub.io/images: |
    - name: vaultwarden
      image: docker.io/vaultwarden/server:1.34.3-alpine
  artifacthub.io/license: MIT
name: vaultwarden
apiVersion: v2
appVersion: 1.34.3
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Vaultwarden is an unofficial Bitwarden-compatible server written in Rust
home: https://lab.frogg.it/doca/vaultwarden-helm
icon: "https://yunohost.org/user/images/bitwarden_logo.png"
keywords:
  - Rust
  - vaultwarden
maintainers:
  - name: Benoît Pourre
    email: benoit.pourre@gmail.com
    url: https://github.com/captnbp
sources:
  - https://lab.frogg.it/doca/vaultwarden-helm
  - https://github.com/dani-garcia/vaultwarden
version: 0.3.2
