{{- if and (not (or .Values.postgresql.enabled .Values.externalDatabase.existingSecret)) (eq .Values.database.type "postgresql") }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "common.names.fullname" . }}-externaldb"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
{{- end }}